version: '3.9'
#alembic upgrade head & 

services:
  usersapi:
    build: ./usersApi
    restart: always
    command: sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --debug"
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
    links:
      - db:db
    networks:
      - merg-app

  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: usersApi
      MYSQL_USER: usersApi
      MYSQL_PASSWORD: usersApi
      MYSQL_DATABASE: usersApi
      #MYSQL_ROOT_HOST: host.docker.internal
    ports:
      - "3306:3306"
    networks:
      - merg-app
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 80s
      retries: 10
    volumes:
      - my-datavolume:/var/lib/mysql
networks:
  merg-app:
    driver: "bridge"
volumes:
  my-datavolume: