version: '3.3'

services:
  usersapi:
    build: ./usersApi
    restart: on-failure
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --debug
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usersApi
      MYSQL_DATABASE: usersApi
    ports:
      - "3306:3306"
